### PR TITLE
add PT bug bounty site

### PR DESCRIPTION
**Pull request by sergiomarotco**
Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [ ] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [ ] All your assets are stored in the **assets** folder.
- [ ] All the images used are in the **PNG** format.
- [ ] Any references to websites have been formatted as [TEXT](URL)
- [ ] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #<insert number here>.

Thank you again for your contribution :smiley:

### CODE REVIEW

**Comment by szh** [comment]
Can you please provide some details and references about this site? Are there any major companies that use this service?

**Comment by mackowski** [comment]
@sergiomarotco this link does not work for me...

**Review by jmanico — APPROVED** [review]

**Comment by szh** [comment]
@jmanico Why did you decide to merge this?

**Comment by jmanico** [comment]
It seemed minor, would you like me to drop it? I am glad to do so. Is it a vendor problem you think?

**Comment by szh** [comment]
I just wasn't able to find any information in English about this site. Do we know it's legit?

**Comment by jmanico** [comment]
I am familiar with them all.

**Comment by szh** [comment]
Ah ok, thanks for clarifying

**Pull request merged**
