### PR TITLE
Various Authorization and Authentication corrections

### PR DESCRIPTION
**Pull request by chrisdlangton**
addresses #686

### CODE REVIEW

**Comment by chrisdlangton** [comment]
There's a programming error in the pipeline unrelated to this contribution.

**Comment by jmanico** [comment]
There is a lot of good work in this PR, but it’s a lot to review all at once.

Can you consider submitting these as many small PR’s so we can make more granular merge decisions?

**Comment by jmanico** [comment]
I can take on splitting this up until multiple PR's. Some of these are great and some are a bit controversial. But I will get to this soon.

**Comment by chrisdlangton** [comment]
> I can take on splitting this up until multiple PR's. Some of these are great and some are a bit controversial. But I will get to this soon.

All over it :+1: 

- Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md #707 
- Docker_Security_Cheat_Sheet.md  #708
- File_Upload_Cheat_Sheet.md #709
- GraphQL_Cheat_Sheet.md #710
- HTML5_Security_Cheat_Sheet.md  #711
- REST_Security_Cheat_Sheet.md #712
- SAML_Security_Cheat_Sheet.md  #713
- Session_Management_Cheat_Sheet.md #714
- Transport_Layer_Protection_Cheat_Sheet.md #715
- Web_Service_Security_Cheat_Sheet.md #716

**Pull request closed without merging**
