### PR TITLE
New Apache HTTPD Cheat Sheet

### PR DESCRIPTION
**Pull request by danehrlich1**
Have an "ideal" apache2.conf. Need to add a little more directives to it, and then comments certainly to explain.

DO NOT YET MERGE

This PR covers issue #05

### CODE REVIEW

**Comment by danehrlich1** [comment]
Again, this is not yet done. Do not merge yet.

**Comment by righettod** [comment]
Hello,
Thanks for the PR.
Do not worry there is a review process applied before any merge.

**Comment by danehrlich1** [comment]
More commits coming tonight. Also going to send out to the Apache listserv for final check.

**Comment by danehrlich1** [comment]
Emailed Apache HTTPD listserv for feedback. Email is as follows:

> All:

I am trying to create an Apache2 security cheatsheet for OWASP.

I am using a monolithic Apache2.conf file (purely for presentation purposes) to show every single security config I can think of that can be used. 

Any suggestions are welcome. I'm sure the document is missing things / has errors currently.

Cheatsheet: https://github.com/danehrlich1/CheatSheetSeries/blob/CSS-05/cheatsheets/Apache_HTTPD_Cheatsheet.md

OWASP Pull Request: https://github.com/OWASP/CheatSheetSeries/pull/184


Best,

Dan Ehrlich

**Comment by ThunderSon** [comment]
@danehrlich1 Hello Dan! Is there anything that we can be of assistance with? Let us know when possible what's your progress on this PR 😄

**Comment by mackowski** [comment]
hey @danehrlich1 do you have any updates on this PR? Do you need our help?

**Comment by ThunderSon** [comment]
As this has been offline for a long duration, this PR will be closed.

**Pull request closed without merging**
