### PR TITLE
Tech Writer: Redid Database Security Cheat Sheet

### PR DESCRIPTION
**Pull request by thornshadow99**
Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [ ] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [ ] All your assets are stored in the **assets** folder.
- [ ] All the images used are in the **PNG** format.
- [ ] Any references to websites have been formatted as `[TEXT](URL)`
- [ ] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #<insert number here>.

Thank you again for your contribution :smiley:

### CODE REVIEW

**Comment by mackowski** [comment]
hey @thornshadow99 good PR! Can you please fix last linter error:
cheatsheets/Authentication_Cheat_Sheet.md:21:291 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]

**Comment by thornshadow99** [comment]
Hi there,

I don't know where that linter error is. I tried to find it but could not.
Could you help me? I'm just a tech writer. :)

Rob

**Comment by jmanico** [comment]
cheatsheets/Authentication_Cheat_Sheet.md:21:291 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]Like 21 row 29--Jim ***@***.***/manicodeSecure Coding EducationOn Feb 18, 2024, at 2:24 PM, RL Thornton ***@***.***> wrote:﻿
Hi there,



I don't know where that linter error is. I tried to find it but could not.

Could you help me? I'm just a tech writer. :)



Rob

**Comment by thornshadow99** [comment]
Thanks!

**Comment by mackowski** [comment]
I will merge that and fix linter in another PR :-) thanks @thornshadow99 for the update!

**Comment by thornshadow99** [comment]
Thanks. I will continue working on cheat sheets and I'll get ahold of
git--that's a promise. :)
Rob

**Pull request merged**
