### PR TITLE
Update Password_Storage_Cheat_Sheet: correct iteration_count number typo

### PR DESCRIPTION
**Pull request by fabienleite**
Hello, as stated in #100, here is my PR for review.

- [x] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [x] All the markdown files do not raise any validation policy violation, see policy [here](https://github.com/OWASP/CheatSheetSeries#editor--validation-policy).
- [x] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries#conversion-rules).
- [x] All your assets are stored in the **assets** folder.
- [x] All the images used are in the **PNG** format.
- [x] Any references to website have been formatted as [TEXT](URL)
- [x] You verified/tested the effectiveness of your contribution (e.g.: defensive code proposed is really an effective remediation? Please verify it works!).
- [x] The CI build of your PR pass, see the build status [here](https://travis-ci.org/OWASP/CheatSheetSeries/pull_requests).

This PR covers Issue #100

### CODE REVIEW

**Comment by righettod** [comment]
Thank you very much for the PR. We will process it ASAP.

**Comment by mackowski** [comment]
I am not sure if this statement is clear to someone who is not familiar with slow-hashing algorithms.

What does it means `computation time on the target system must take at least 1 second`. What is target system and why 1 second? If target system is attacker system it make sense to make it about 1 second but developer does not have capabilities to check it. On the other hand if target system is your application server I do not fully agree with this statement.

**Comment by righettod** [comment]
It is the main issue with pbkdf2, as it is not time computation constant,
you cannot ensure that the setting to take 1 sec on your server will take
also 1 sec on an attacker machine. Here, the goal is to made aware of that
point, people that decide to use pbkdf2. Usage of Argon2 is highly
recommanded.

**Comment by mackowski** [comment]
But in current form this is not clear for me. For example I do not understand what is `target system` in this case. Maybe I should read it one more time...
Anyway maybe if the goal is to made aware that pbkdf2 is not time constant, instead of telling that you should `must have a number implying that the computation time on the target system must take at least 1 second.` or `test the appropriate number for your specific situation` (what is impossible) we should just write that `pbkdf2 is not time constant and therefore is hard to asses number of iterations etc.`

**Comment by mackowski** [comment]
Apologies I read it one more time and it is better than I thought.

**Comment by righettod** [comment]
No problem @mackowski it's very important to share the different opinions on this point 😃

**Pull request merged**
