### PR TITLE
Add MASVS index

### PR DESCRIPTION
**Pull request by cpholguera**
Added MASVS index mapping to useful Cheat Sheets.

### CODE REVIEW

**Comment by mackowski** [comment]
Wow, nice :) thank you @cpholguera - this PR also show that we need to add some content for V6 and V8

**Comment by mackowski** [comment]
To add new page (outside of cheatsheets directory) we also need to update generating the MkDocs. I think that these three PR can help with that:
 - https://github.com/OWASP/CheatSheetSeries/pull/735
 - https://github.com/OWASP/CheatSheetSeries/pull/736
 - https://github.com/OWASP/CheatSheetSeries/pull/737
If you do not want to do that I can make another PR with changes to the site generation :)

**Review by mackowski — APPROVED** [review]

**Comment by mackowski** [comment]
Looks good. I will merge and build it.

**Comment by mackowski** [comment]
@cpholguera it is live https://cheatsheetseries.owasp.org/IndexMASVS.html :-)

**Comment by cpholguera** [comment]
Awesome @mackowski, thanks a lot! We'll announce it soon in our official accounts 🙌

**Comment by cpholguera** [comment]
After seeing it rendered I noticed some minor things to be fixed. Here they are fixed: https://github.com/OWASP/CheatSheetSeries/pull/856

**Comment by mackowski** [comment]
@cpholguera https://github.com/OWASP/CheatSheetSeries/pull/856 was merged and should be in prod

**Pull request merged**
