### PR TITLE
Secure Cloud Architecture cheat sheet

### PR DESCRIPTION
**Pull request by Josh-Beck**
### Hello!

I took the liberty of creating this sheet, even though the `ack` hadn't been finalized yet. Because of this, there may be topics to cover or remove, so please let me know.

Referencing ticket #1148

### CODE REVIEW

**Review by jmanico — DISMISSED** [review]
very mature work

**Comment by jmanico** [comment]
The linter failed again - can you take a look @Josh-Beck ? Thank you! We'll get this merged soon!

**Comment by jmanico** [comment]
/home/runner/work/CheatSheetSeries/CheatSheetSeries/cheatsheets/Secure_Cloud_Architecture.md
   29:29   ✓ error  Incorrect usage of the term: “built in”, use “built-in” instead      terminology
   35:642  ✓ error  Incorrect usage of the term: “built in”, use “built-in” instead      terminology
  189:17   ✓ error  Incorrect usage of the term: “Ids”, use “IDs” instead                terminology
  [23](https://github.com/OWASP/CheatSheetSeries/actions/runs/5379938361/jobs/9865790395?pr=1152#step:5:24)7:3    ✓ error  Incorrect usage of the term: “3rd party”, use “Third-party” instead  terminology

**Comment by kwwall** [comment]
@jmanico - TIL the linter we are using is really anal. 🤣

-kevin

**Comment by Josh-Beck** [comment]
@jmanico Thanks for letting me know, this should (hopefully) be the last one 😄

**Review by szh — DISMISSED** [review]

**Comment by szh** [comment]
This looks great. I'm going to wait for another reviewer to approve as well since it's a significant addition. CC @jmanico @kwwall @mackowski

**Comment by kwwall** [comment]
@szh - Cloud security is not my strong suite, so I don't have any opinions either way. I do have a former colleague who has a LOT of cloud security expertise though that I could ask to review this if you need an extra pair of eyes on it though. Just let me know.

**Comment by utilimatt** [comment]
Hi everybody! Thank you so much for the opportunity to review, and hopefully contribute to such an amazing project!
Here are my comments, please let me know which you would like to retain, and I can add them as commits to this PR.
[OWASP Secure Cloud Architecture Review.md](https://github.com/OWASP/CheatSheetSeries/files/11972377/OWASP.Secure.Cloud.Architecture.Review.md)

**Comment by szh** [comment]
@utilimatt Thank you for this detailed review! I'll let @Josh-Beck decide which comments to incorporate for this PR. I do think we should have follow up PRs to address any of the points that don't make it in this PR.

**Comment by utilimatt** [comment]
Thank you so much @kwwall, @szh & @Josh-Beck for this opportunity to help out!
It's always been a dream of mine to contribute to a project like this, and I'd love to help again if the desire arises.

**Comment by Josh-Beck** [comment]
Yeah @utilimatt this review was incredible!

I have made most of the changes from the  "might do this instead" and "typos" section. Specifically, thanks for calling out the "Some Trust" diagram, I mixed up the trust boundaries (oops). 

### Please Review
To that point, @utilimatt can you please review the trust boundary section again? I made the diagrams more generic, accounting for IAM and other auth mechanisms, but I don't want to lose the initial intent.


### Future PRs?
@jmanico @szh 
How should we handle the "new section" comments? Would those be enhancement PRs like szh mentioned, or should some of them make their way into this one as must haves for an initial release? I can speak to some of these subjects, but others will be beyond my comfortable knowledge.

**Comment by utilimatt** [comment]
Thanks @Josh-Beck! I'll check out the diagrams right now.

**Comment by utilimatt** [comment]
@Josh-Beck I reviewed the diagrams, and they look great!
Only 2 things I found:
1. The total trust diagram (diagram number 3) doesn't have any arrows pointing to the Auth solution.
2. For the some trust diagram (diagram number 4) I had kind of a hard time figuring out what was going on there for the auth flow. I wrote up a quick diagram that models out an API Gateway, a Lambda, and a managed database. Its quite a bit more verbose so probably not awesome for a cheat sheet, but I think it tells the auth flow story for what is one of the most common design patterns, and you can clearly see the departure from traditional networking patterns on how the writes ultimately get authorized to the database instance.
SomeTrust

**Comment by Josh-Beck** [comment]
@utilimatt - Thanks for the quick feedback :)

> 1. The total trust diagram (diagram number 3) doesn't have any arrows pointing to the Auth solution.

This was intentional to show the lack of common security components in the architecture, and describe what could be considered "wasteful" in terms of having auth mechanisms available and not using them *(assuming a business has paid for auth and then a developer skips it, relying on trust instead)*. Do you think there is a better way to outline this, or is there a way to maintain the "total trust" thesis while adding some arrows?

-------


> For the some trust diagram (diagram number 4) I had kind of a hard time figuring out what was going on there for the auth flow. I wrote up a quick diagram...

This diagram is awesome, but I struggled a bit to distill it into a simple form for the cheatsheet like you indicated. I agree that an ephemeral access model for storage access is the right way to go, as before I was using more of a web auth model for the storage (which doesn't make much sense). 

I ended up ditching the "business criticality" from the diagram and added ephemeral IAM. I am not mentioning the control plane because the goal is to discuss the routing the request makes through trust zones, making the assumption that every resources knows where to go. **This may be a bad assumption**, but I'm making it for simplicity. 

Thoughts?


*(I also took the liberty of adding you to the contributor list for this one, hope that's alright 😄 )*

**Comment by utilimatt** [comment]
@Josh-Beck Makes perfect sense to me, on both comments, and bonus points on noting that auth is not included by default, and making it visual!
Thanks for putting this together, and letting me be a part of it! 
Also HUGE thank you for adding me to contributors!
If there's anything else I can do just let me know!
I can be reached pretty reliably on LinkedIn DM since I need to update my email for GitHub so I might miss callouts: https://www.linkedin.com/in/matt1337/

**Comment by jmanico** [comment]
> @jmanico - TIL the linter we are using is really anal. 🤣

Agreed, it's to keep folks like you (and your wild markdown) in line.

**Pull request merged**
