### PR TITLE
CSRF mitigations using non-simple requests

### PR DESCRIPTION
**Pull request by jackevans43**
This PR covers issue #1309 
---

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [x] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [ ] All your assets are stored in the **assets** folder.
- [ ] All the images used are in the **PNG** format.
- [x] Any references to websites have been formatted as `[TEXT](URL)`
- [x] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

### CODE REVIEW

**Comment by jackevans43** [comment]
@mackowski

**Review by jmanico — CHANGES_REQUESTED** [review]
I'm a little hesitant to put browser bug in my threat model....

**Comment by jackevans43** [comment]
@jmanico Would you be happy if I just removed the link to the bug? The text about browser bugs was almost entirely copied from the existing text, with the addition of the specific example where the content type was not enforced.

**Comment by jmanico** [comment]
Please :)

**Comment by jackevans43** [comment]
@jmanico Done!

**Review by jmanico — APPROVED** [review]

**Pull request merged**
