### PR TITLE
Rename Application_Logging_Vocabulary_Cheat_Sheet.md to Logging_Vocabulary_Cheat_Sheet.md

### PR DESCRIPTION
**Pull request by mackowski**
Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [x] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [x] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [x] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [x] All your assets are stored in the **assets** folder.
- [x] All the images used are in the **PNG** format.
- [x] Any references to websites have been formatted as [TEXT](URL)
- [x] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [x] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #762

### CODE REVIEW

**Comment by jmanico** [comment]
Hey @mackowski can you put the old CS back in and just redirect to the new one so old URL's are not broken? Pretty please?

**Comment by mackowski** [comment]
@jmanico we can add additional redirects so e.g. add old URL. Here is the code for it https://github.com/OWASP/CheatSheetSeries/blob/master/scripts/Generate_Site_mkDocs.sh#L93 do you want to try it? And learn how it works?

**Comment by jmanico** [comment]
I know how to do it I was just trying to get you to do it. I'm so crazy 
busy this week teaching but ran into the older broken link a few times. 
But I'll get to it if you cannot good sir.

And I hope you and your family are well! :) :)

**Comment by mackowski** [comment]
@jmanico I will fix it :) PR is here: https://github.com/OWASP/CheatSheetSeries/pull/786

**Comment by mackowski** [comment]
@jmanico it is live now old link https://cheatsheetseries.owasp.org/cheatsheets/Application_Logging_Vocabulary_Cheat_Sheet.html is redirecting to new page :)

**Comment by jmanico** [comment]
You are fantastic, thank you!

**Pull request merged**
