### PR TITLE
Add threats against logs

### PR DESCRIPTION
**Pull request by lucasgonze**
Add section on threats against logs.

This PR covers issue #87.

Signed-off-by: Lucas Gonze <lucas@gonze.com>

### CODE REVIEW

**Comment by jmanico** [comment]
You rock!

**Comment by jmanico** [comment]
This is a great PR but the linter is failing, can you check those errors out please? :)

**Comment by lucasgonze** [comment]
Fixed issues and repushed. No failing checks.

**Comment by lucasgonze** [comment]
🍾

**Pull request merged**
