### PR TITLE
Fixed indentation

### PR DESCRIPTION
**Pull request by mkrjn99**

### CODE REVIEW

**Review by jmanico — APPROVED** [review]

**Comment by jmanico** [comment]
I'm still seeing link errors :( 

cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md:82:1 MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]
cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md:83:1 MD007/ul-indent Unordered list indentation [Expected: 4; Actual: 2]

**Comment by mkrjn99** [comment]
Updated, please have a look again.

**Review by mackowski — APPROVED** [review]

**Review by szh — APPROVED** [review]
LGTM, thank you!

**Comment by mkrjn99** [comment]
Though, I do not see the indentation fix on the website, is there a cycle with which these changes are pushed to prod?

**Comment by jmanico** [comment]
It should go live immediately after a merge unless our deployment automation is broken.

I’m out of position in the middle of a move but will look into it in a few days.

**Comment by jmanico** [comment]
I have that permission I think. I am overwhelmed moving to Europe right now but will look at it as soon as I can.

**Comment by mackowski** [comment]
@mkrjn99 it should be live now ;-)

**Pull request merged**
