### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by Naramsim**
Hello, this PR: 

1. Actually highlights code blocks. Before, code blocks weren't hightlighted. This brings in a new dependency `Pygments`.
2. Add a `venv` folder to gitignore, handy for virtualenv users
3. Simplifies Github Action by using `make` command and suppressing an unneeded `chmod`
4. Document how to build and view the website locally in the README
5. Formats the HTML code of `404.html` and adds a link to the homepage for lost users
6. Removes a broken link warning

👋

### CODE REVIEW

**Comment by mackowski** [comment]
Thanks @Naramsim for this PR! I will review it in 1-2 days but looks good.

**Review by mackowski — APPROVED** [review]

**Comment by mackowski** [comment]
Thank you @Naramsim again! there is plenty of smart people that are making changes to the cheatsheets but not a lot that are improving website and code behind it! 
CC: @jmanico :)

**Comment by Naramsim** [comment]
No problem, anything else I could look into?

**Comment by mackowski** [comment]
There is an issue opened by you #677 
We also have one GT action failing https://github.com/OWASP/CheatSheetSeries/actions/workflows/publishing-check.yml 
But in general, if you have any ideas how the page can be improved, we are welcome to the changes :-)

**Comment by jmanico** [comment]
Thank you @Naramsim !!!

**Pull request merged**
