### PR TITLE
New Addition: Infrastructure as Code Security Cheatsheet

### PR DESCRIPTION
**Pull request by ragashreeshekar**
This PR illustrates the topics of concern when developing, distributing and deploying IaC also when they are in production. This is intended to provide topics to concentrate on while adopting security shift-left in IaC and it is intended to be language/technology agnostic.

### CODE REVIEW

**Review by jmanico — APPROVED** [review]
This looks like a very solid start!

**Comment by mackowski** [comment]
@jmanico why you closed this? I would like to have the PR open until we will be ready to add this to cheatsheets. Now it will be hard to collaborate. It is easy to make a comments and discussion in the open PR, it is much harder to do it now.

**Comment by mackowski** [comment]
@ragashreeshekar I reverted the merge to the drafts and I created new PR #648. If you want to open new one so in the history it will be associated with you and Nokia please do so and we will delete my PR.

**Comment by jmanico** [comment]
My mistake open it back up!!!

**Pull request merged**
