### PR TITLE
Elie's Resignation

### PR DESCRIPTION
**Pull request by ThunderSon**
Kindly merge when possible

### CODE REVIEW

**Comment by jmanico** [comment]
I got this, I want to promote Jakub as well so I’ll commit my changes to master directly when I get access.

Thank you.
--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by ThunderSon** [comment]
You already have Admin accesses as you're part of the CSS admins group :)
I have revoked mine and rbsec's accesses. Let me know if there's anything additional needed from my side.

**Comment by jmanico** [comment]
handled with a direct commit to master

**Comment by ThunderSon** [comment]
Kindly remove me and rbsec from the CODEOWNERS file as found in the PR. Thanks.

**Pull request closed without merging**
