### PR TITLE
Address GitHub issue #1092

### PR DESCRIPTION
**Pull request by kwwall**
I think this PR could still use a lot of work, especially to be made a bit more succinct. Unfortunately, my middle name is "TL;DR", so I'm not the best one for a day job at _Reader's Digest_, but surely one of our reviewers have those mad skills.

For the most part, this is largely based on ESAPI wiki post, [XSS Defense: No Silver Bullets](https://github.com/ESAPI/esapi-java-legacy/wiki/XSS-Defense:-No-Silver-Bullets), which I wrote a while ago. That is why there are ESAPI code references here. That's because that is the output encoder that I'm most familiar with. (Duh!)  If @jmanico wants to switch them to use the equivalent member function calls from the OWASP Java Encoder project, I have no objections.

I have allowed direct edits to this PR by the CS maintainers, so if you have something to fix, just have at it. And regarding something to "fix", if this is too long, we could consider collapsible sections. That's up to the CS reviewers.

Note, if there are linter errors, I will check them in the build status logs and address them in a subsequent commit.

This PR covers issue #1092

### CODE REVIEW

**Comment by kwwall** [comment]
Sure would be nice if it showed all the f'ing lint errors at once. Sigh. If it didn;t require npm to run, I'd run it locally first.

**Comment by otkd** [comment]
> Sure would be nice if it showed all the f'ing lint errors at once. Sigh. If it didn;t require npm to run, I'd run it locally first.

@kwwall I've found this VSCode extension to work pretty well: https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

**Comment by jmanico** [comment]
Kevin, can you professionalize this a bit? "a silver bullet to slay their XSS werewolves if you will." throws me off a little.

**Comment by kwwall** [comment]
@jmanico - Yeah, agree. That doesn't make any sense apart from the original ESAPI wiki page title, which was ""XSS Defense: No Silver Bullets" and was an homage to Frederick Brooks' classic article "[No Silver Bullet: Essence and Accidents of Software Engineering](https://www.cs.unc.edu/techreports/86-020.pdf)" that was posted in the _IEEE_ _Computer_ in April, 1987. I meant to remove it, but just forgot.

**Pull request merged**
