### PR TITLE
Update .NET guidance based on feedback from @relaxnow

### PR DESCRIPTION
**Pull request by tghosth**
Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

Please make sure that for your contribution:

- [ ] ~~In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries~/blob/master/templates/New_CheatSheet.md).~~
- [x] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [x] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [ ] ~~All your assets are stored in the **assets** folder.~~
- [ ] ~~All the images used are in the **PNG** format.~~
- [ ] ~~Any references to websites have been formatted as [TEXT](URL)~~
- [x] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [x] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

This PR covers issue #788.

### CODE REVIEW

**Comment by jmanico** [comment]
So far so good....

**Comment by jmanico** [comment]
This is in draft mode and I cannot merge it yet....

**Comment by tghosth** [comment]
Yeah I was hoping to get some further comments from @relaxnow, let's give it a few more days...

**Comment by jmanico** [comment]
Hello @relaxnow can you take a look at our proposed change? Thank you!

**Comment by jmanico** [comment]
Shall we push it @tghosth ?

**Comment by relaxnow** [comment]
Hi, sorry for ignoring this, I sent an email to @tghosth and closed this case. For transparencies sake I'll post the relevant parts of that email here:

> As I mentioned before though, the main problem with tainted input in Windows commands is that they all do their own parsing, you can read more here: https://gist.github.com/Zenexer/40d02da5e07f151adeaeeaa11af9ab36 . If you’re calling a Windows application you can’t ever be fully confident what it considers special characters (for example, some Windows commands consider “@” a special character, some don’t) without knowing how the application called parses arguments.
> Frequently, we see this being used with arbitrary services (for example third party services that perform some special function like image or video manipulation).
> 
> I would stick with my original recommendation:
> 
> In general our primary recommendation for this is to see if it is possible to (1) use something other than command execution, for example, calling an application API.
> If this is not possible we recommend (2) strictly limiting input to alphanumerics. If this is not possible, you might consider (3) encrypting the data with something like AES ( https://docs.microsoft.com/en-us/dotnet/standard/security/encrypting-data ) or (4) encoding the data with something like Base64 ( https://docs.microsoft.com/en-us/dotnet/api/system.convert.tobase64string?view=netframework-4.5.2 ).

**Comment by jmanico** [comment]
Can we go live with this now? :)

**Comment by tghosth** [comment]
My sincere apologies to @relaxnow who emailed me ages ago and my indecision paralysis meant it fell between the cracks...

Having contemplated @relaxnow 's feedback further, I think he is correct that we cannot provide any security guarantees at this point and we will therefore have to just rely on warnings and general guidance.

@jmanico @relaxnow do you have any feedback on the final changes i have made here?

**Comment by tghosth** [comment]
@jmanico I am going to mark as ready for merging with no further feedback so far

**Comment by jmanico** [comment]
> @jmanico can this now be merged?

Why yes

**Comment by jmanico** [comment]
Thank you all for this effort!

**Pull request merged**
