### PR TITLE
Release a Network segmentation Cheat Sheet?

### PR DESCRIPTION
**Pull request by sergiomarotco**
Try to release Network segmentation Cheat Sheet from https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets_draft/Network_Segmentation_Cheat_Sheet.md

Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [x] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [x] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [x] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [x] All your assets are stored in the **assets** folder.
- [x] All the images used are in the **PNG** format.
- [x] Any references to websites have been formatted as [TEXT](URL)
- [x] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #<insert number here>.

Thank you again for your contribution :smiley:

### CODE REVIEW

**Comment by AgoraSecurity** [comment]
I think it makes more sense if this PR is a file mv ([git mv](https://git-scm.com/docs/git-mv)) instead of a new file

**Comment by mackowski** [comment]
@sergiomarotco can you please add ".md" at the end of the file?

**Comment by jmanico** [comment]
This is great but can you add it to the draft folder while we review if you want to merge it now?

**Review by jmanico — APPROVED** [review]

**Comment by sergiomarotco** [comment]
C7D17A63-B398-4544-B0C5-F9487FDB4E0E
Why images not visible on site owasp.org?

**Comment by AgoraSecurity** [comment]
My hunch is that it's because lint is failing: https://github.com/OWASP/CheatSheetSeries/actions/runs/3825640619/jobs/6508782030

**Comment by jmanico** [comment]
I fixed all of these links, better?

**Comment by sergiomarotco** [comment]
> I fixed all of these links, better?

It seems so

**Comment by sergiomarotco** [comment]
@jmanico 

https://cheatsheetseries.owasp.org/cheatsheets/Network_Segmentation_Cheat_Sheet.html#three-layer-network-architecture
image

**Comment by sergiomarotco** [comment]
https://cheatsheetseries.owasp.org/cheatsheets/Network_Segmentation_Cheat_Sheet.html#introduction
image

**Pull request merged**
