### PR TITLE
Fix some grammar mistakes in 'Denial of Service'

### PR DESCRIPTION
**Pull request by devraza**
I haven't checked over the entire cheat sheet, but most of it.

### CODE REVIEW

**Review by jmanico — COMMENTED** [review]
Please run these changes through grammarly or AI. statements like "any single points" are a bit jarring a just a little cleanup would help.

**Review by szh — APPROVED** [review]
LGTM

**Review by jmanico — APPROVED** [review]

**Comment by jmanico** [comment]
Are two reviewers enough to merge or do we need all three of us?

**Comment by szh** [comment]
@jmanico Two. The repo is intentionally configured that it only allows merging after 2 reviewers, but since you're an admin it allows you to override that. It's just best not to do that unless there's a strong reason to do so.

**Pull request merged**
