### PR TITLE
Added Kubescan to Rule 9

### PR DESCRIPTION
**Pull request by KellyGriffin**
Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries#editor--validation-policy).
- [ ] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries#conversion-rules).
- [ ] All your assets are stored in the **assets** folder.
- [ ] All the images used are in the **PNG** format.
- [ ] Any references to websites have been formatted as [TEXT](URL)
- [ ] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://travis-ci.org/OWASP/CheatSheetSeries/pull_requests).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #<insert number here>.

Thank you again for your contribution :smiley:

### CODE REVIEW

**Comment by rbsec** [comment]
Hi @KellyGriffin - thanks for the PR.

This tool looks to be fairly new and still under quite active development - so we need to consider whether it's mature and stable enough to be recommending in this CS. It's not a tool that I've used personally. @ThunderSon or @mackowski - have either of you come across this?

**Comment by mackowski** [comment]
I would love to have a comparison between tools. I am not against new tools but we should have a reason when we recommend more than two tools. Why is it better, how it is different from other tool etc.
Something simillar to what [trivy](https://github.com/aquasecurity/trivy#comparison-with-other-scanners) have on their github.

@rbsec what do you think?

@KellyGriffin are you able to create such comparison?

**Comment by rbsec** [comment]
I wouldn't be against a brief summary - but you could probably write an entire article comparing these types of tools, which isn't really what that cheat sheets about.

**Comment by KellyGriffin** [comment]
@mackowski @rbsec essentially the reason I added Kube-scan on there, whilst agree its still very new, has a different use case and outcome.  Kube-scan focuses on showcasing Kubernetes Common Configuration Scoring System which is very similar to CVSS which gives ratings, etc.

**Comment by mackowski** [comment]
@KellyGriffin we decided that currently we cannot recommend kube-scan because other tools are more matured and battle proved. 

This cheatsheet is for Docker containers and not for k8s. kuba-scan adds a value (e.g. Kubernetes Common Configuration Scoring System) and a lot of checks against k8s configuration and it might be a good fit for k8s CS (after such CS will be created).

**Pull request closed without merging**
