### PR TITLE
Update Threat_Modeling_Cheat_Sheet.md

### PR DESCRIPTION
**Pull request by Mohfateh**
Finalizing all TO-DO sections.
Updating references in the appendix and updating all URLs in the sheet.
Adding references to the OWASP TM Cookbook & Mozilla SeaSponge.

Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [ ] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [ ] All your assets are stored in the **assets** folder.
- [ ] All the images used are in the **PNG** format.
- [ ] Any references to websites have been formatted as [TEXT](URL)
- [ ] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #<insert number here>.

Thank you again for your contribution :smiley:

### CODE REVIEW

**Review by mackowski — CHANGES_REQUESTED** [review]
@Mohfateh I reviewed it and looks good. I have two questions:
1. Where can we put reference to the threat modeling manifesto? It is also a valuable resource that can help the readers. 
2. Can you review this draft https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets_draft/Threat_Modeling_Cheat_Sheet.md and see if there is something that you would like to add/use here?

**Comment by jakubmackowski** [comment]
@Mohfateh please also review lint errors and fix them

**Comment by mackowski** [comment]
@Mohfateh please also fix all linter errors

**Comment by Mohfateh** [comment]
Hi Jakup,
I'll work on it this weekend and share an updated version.

**Comment by mackowski** [comment]
Nice! I am merging it! Thank you @Mohfateh!

**Review by mackowski — APPROVED** [review]

**Pull request merged**
