### PR TITLE
HTML5 CS Grammar Update

### PR DESCRIPTION
**Pull request by Zaelot**
A Pull Request to the Cheat Sheet Series. 

Please make sure that for your contribution:

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [x] All the markdown files do not raise any validation policy violation, see policy [here](https://github.com/OWASP/CheatSheetSeries#editor--validation-policy).
- [x] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries#conversion-rules).
- [x] All your assets are stored in the **assets** folder.
- [x] All the images used are in the **PNG** format.
- [x] Any references to website have been formatted as [TEXT](URL)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: defensive code proposed is really an effective remediation? Please verify it works!).
- [x] The CI build of your PR pass, see the build status [here](https://travis-ci.org/OWASP/CheatSheetSeries/pull_requests).

### CODE REVIEW

**Comment by righettod** [comment]
Thanks you very much for the PR 😃

**Comment by Zaelot** [comment]
There's more to proofread and improve there, but I'm too exhausted from my regular workday to catch those. (Is there a way to mark suspicious parts for the other members of the community to review/interact with those? Something like the Talk page on Wikipedia?)

**Comment by ThunderSon** [comment]
@Zaelot That's what issues and PRs are for :) I'll rename the PR to reflect to what you did. If you need to discuss something, kindly join us on [slack](owasp.slack.com)

**Comment by righettod** [comment]
@Zaelot Take rest and care of you, all the team thanks you very much for your contribution 😃

**Pull request merged**
