### PR TITLE
New Addition: Infrastructure as Code Security Cheatsheet

### PR DESCRIPTION
**Pull request by ragashreeshekar**

### CODE REVIEW

**Review by jmanico — APPROVED** [review]
I absolutely love the direction on this work!

**Comment by jmanico** [comment]
I just want to say I am very excited about the potential of this cheatsheet!!

**Comment by ykcab** [comment]
I am curious about the license used (embedded) in this file. @jmanico, what's the standard license does OWASP uses: Apache or GNU GPL?

**Comment by jmanico** [comment]
Creative Commons for document projects, and varied licenses for code projects. Happy to dig more. The cheatsheet series is Creative Commons.

**Comment by ykcab** [comment]
@ragashreeshekar do you mind removing that Nokia license added in the file?

**Comment by ragashreeshekar** [comment]
@ykcab This is the instructions I have received from Opensource contributions review board, Nokia. I may not be able to override it. Is there any concern around it? Could you please elaborate

**Comment by ykcab** [comment]
@ragashreeshekar, thank you for elaborating that. If it won't cause any issue in the long run, then we keep it. These things sometimes do come with a cost and we may be surprised so it is important to keep that in mind. Many licenses claim to be free but when you mix them with other licenses within the same project it becomes an issue.

**Comment by jmanico** [comment]
> @ykcab This is the instructions I have received from Opensource contributions review board, Nokia. I may not be able to override it. Is there any concern around it? Could you please elaborate

The document as Creative Commons is in sink with our license requirements. However, the Nokia Copyright is not. Over time, other contributors will modify these works as part of any open source project and Nokia will not have a copyright on those additional modifications. So my request is that we change the license to just:

**Licensed under the Creative Commons Attribution Share Alike 3.0 Unported License 
SPDX-License-Identifier: CC-BY-SA-3.0**

What we can do is mention in the article that this work was donated to OWASP by Nokia so your efforts are acknowledged.

**Comment by CsatariGergely** [comment]
@jmanico @mackowski I'm working for Nokia OSPO and I'm the source of @ragashreeshekar -s instructions. Having a copyright statement in the file is just an explicit description of the reality. With the license Nokia gives you right to use the content, but the copyright remains with Nokia. What we donate is the license to use Nokia copyrighted material not the copyright itself. It is better to have an explicit list of copyright holders in the files, than some vague description. If later someone else is contributing to the same file, they can add their copyright notice in addition or amend the already existing one.

**Comment by mackowski** [comment]
@CsatariGergely all cheatsheets are now under [CC BY-SA 4.0 licence](https://creativecommons.org/licenses/by-sa/4.0/) - this licence is very similar to CC-BY-SA-3.0. Can we update the licence to  CC BY-SA 4.0? It would be weird to have one file with different licence than all others.
IMO we can keep the license lines in the file, no problem for me.
@jmanico what do you feel about it?

**Comment by CsatariGergely** [comment]
@mackowski @jmanico Your [LICENSE file](https://github.com/OWASP/CheatSheetSeries/blob/master/LICENSE.md) points to CC-BY-SA 3.0.

**Comment by mackowski** [comment]
@CsatariGergely you are right, I need to fix the main readme.md file. So, in that case I am ok with that.

**Comment by mackowski** [comment]
@jmanico 2 questions for you to decide:
1. Can we leave this licencing lines? As I said I do not see issues with that.
2. Can we move it from drafts to main folder? I see that this can be improved over time, but it is a good work and I think that publishing it in the current form 1) will help some people 2) will get some PRs and ideas how to build on top of it.

**Comment by jmanico** [comment]
I say yes to both. :) Works for me. I really love this work as well.

- Jim

> @jmanico <https://github.com/jmanico> 2 questions for you to decide:
>
>  1. Can we leave this licencing lines? As I said I do not see issues
>     with that.
>  2. Can we move it from drafts to main folder? I see that this can be
>     improved over time, but it is a good work and I think that
>     publishing it in the current form 1) will help some people 2) will
>     get some PRs and ideas how to build on top of it.
>

**Comment by jmanico** [comment]
The current Nokia license is creative commons, and that alone is enough for me to support leaving it as is - it allows for collaboration and that's all we need :)

**Comment by ykcab** [comment]
Thanks, everyone!

**Pull request merged**
