### PR TITLE
Restructured section 2, added enclaves and cloud based HSM

### PR DESCRIPTION
**Pull request by DrRetsiemsuah**
This pull request is an extension of the previously raised PR #842 and includes feedback from @commjoen.

### Structure
**Section 2**

* Merged "Remove Human Interaction" (2.4) with 2.8 to "2.4 Automate Secrets Management"
* Merge "Use Least Privilege (2.4)" with 2.3 to "2.3 Access Controls"

### Content
**Section 2.6.2**

Added exclusion for user credentials according to e.g. NIST guidelines nowadays suggest that passwords should only be rotated, if there is evidence for compromise ([NIST Special Publication 800-63B](https://pages.nist.gov/800-63-3/sp800-63b.html#:~:text=Do%20not%20require%20that%20memorized%20secrets%20be%20changed%20arbitrarily%20(e.g.%2C%20periodically)%20unless%20there%20is%20a%20user%20request%20or%20evidence%20of%20authenticator%20compromise.%20(See%20Section%205.1.1%20for%20additional%20information)))

**Section 2.11**

Added metadata “By whom it was created/consumed/archived/rotated/deleted” (referring to Auditing requirements)

**Section 3.2**

Added GCP Secret Manager ([Secret Manager | Google Cloud](https://cloud.google.com/secret-manager))

**Section 4**

* Added 4.1.1.1 AWS Nitro Enclaves
* Added 4.1.1.2 AWS CloudHSM
* Added 4.1.2.1 Google Cloud Confidential Computing
* Added 4.1.3.1 Azure Confidential Computing
* Added 4.1.3.2 Azure Dedicated HSM

### CODE REVIEW

**Comment by commjoen** [comment]
Hope to have time to review soon, but might take a week or 2 as i have a temp laptop ATM, anyone else wants to review first?

**Comment by jmanico** [comment]
2 notes:

1) Input validation will not always save you, it depends what characters you let through even in an allow list. If you are adding data to a command, OS level escaping is the answer (and quoting the data).

2) There is a lint error in your PR, can you look at that as well?

**Review by jmanico — APPROVED** [review]

**Comment by jmanico** [comment]
The link checker failed, can you kindly fix and Ill push this?

**Comment by DrRetsiemsuah** [comment]
Yeah, for sure - going to resolve the issue and double-check on the input validation. However, it may take some time as I'd reach out to the person who pushed the input validation initially.

**Comment by jmanico** [comment]
Im going to commit this and fix the lint stuff myself :)

**Pull request merged**
