### PR TITLE
Update Transport_Layer_Security_Cheat_Sheet.md

### PR DESCRIPTION
**Pull request by stellastrareviews**
Added Stellastra's Cipher Suite Checker

Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [x] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [x] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [x] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [x] All your assets are stored in the **assets** folder.
- [x] All the images used are in the **PNG** format.
- [x] Any references to websites have been formatted as `[TEXT](URL)`
- [x] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [x] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #<insert number here>.

Thank you again for your contribution :smiley:

### CODE REVIEW

**Review by jmanico — APPROVED** [review]

**Comment by szh** [comment]
Can you please provide some background about this service? Is it a well trusted player in the industry?

**Comment by jmanico** [comment]
Since we have other commercial offerings on this list, with hesitation, did accept this.

"Stellastra has established itself as a notable platform in the cybersecurity field, particularly for its comprehensive evaluation and ranking of cybersecurity companies worldwide. It compares over 7,000 companies across various categories, including DMARC, email security, and TLS analysis, using metrics like relevancy, popularity, security scoring, and focus within specific domains​"

**Comment by kwwall** [comment]
> Since we have other commercial offerings on this list, with hesitation, I did accept this.
> 
> "Stellastra has established itself as a notable platform in the cybersecurity field, particularly for its comprehensive evaluation and ranking of cybersecurity companies worldwide. It compares over 7,000 companies across various categories, including DMARC, email security, and TLS analysis, using metrics like relevancy, popularity, security scoring, and focus within specific domains​"

As long as that glowing review didn't come from stellastra.com ;-)

**Comment by jmanico** [comment]
That was me and I have zero affiliation with the company. It was a AI hit and may just be marketing, I am happy to remove this if you folks think that is best.

**Comment by kwwall** [comment]
@jmanico - No worries; JK.

**Comment by stellastrareviews** [comment]
Thanks for your consideration. WRT trust we have been recognized by Bugcrowd, Pentest-Tools.com, PowerDMARC, Cohesity, and others. @szh, the link could also be edited to show our breakdowns of 300+ cipher suites: https://stellastra.com/cipher-suite

**Review by mackowski — APPROVED** [review]

**Comment by mackowski** [comment]
Looks that someone must decide :-) We have other similar links here, results from scanning looks ok. I will merge that

**Pull request merged**
