### PR TITLE
Error handling CS: Fixing typos

### PR DESCRIPTION
**Pull request by JonnySchnittger**
Thank you for submitting a Pull Request to the Cheat Sheet Series. 

Please make sure that for your contribution:

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see policy [here](https://github.com/OWASP/CheatSheetSeries#editor--validation-policy).
- [ ] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries#conversion-rules).
- [ ] All your assets are stored in the **assets** folder.
- [ ] All the images used are in the **PNG** format.
- [ ] Any references to website have been formatted as [TEXT](URL)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://travis-ci.org/OWASP/CheatSheetSeries/pull_requests).

If your PR is related to an issue. Please end your PR text with the following line:

```
This PR covers issue #<insert number here>.
```

Thank you again for your contribution :smiley:

### CODE REVIEW

**Comment by ThunderSon** [comment]
Thank you for spotting this mistake! Might you be able, while going through the doc, check if any other grammar mistakes exist?

**Comment by JonnySchnittger** [comment]
I can :) it'll take me awhile though lol

**Comment by ThunderSon** [comment]
No rush at all! We're more than welcome for improvements in the cheat sheets.

**Comment by righettod** [comment]
Hello,

In order to make the project going forward and no keep PR open for a too long time,  we will close this PR next week if no update are pushed.

Thank you very much in advance for your understanding 😃

**Comment by righettod** [comment]
I merge it. Another PR will be open in case of need.

**Pull request merged**
