### PR TITLE
XSS CS Update

### PR DESCRIPTION
**Pull request by rdela**
This PR covers issue #101

Update JS/Node.js libs in Cross Site Scripting Prevention Rule 6 "Other libraries that provide HTML Sanitization":

Line 344 linked to [ecto/bleach](https://github.com/ecto/bleach) as "JavaScript/Node.js Bleach"

Now Line 344-5 link to:
- [cure53/DOMPurify](https://github.com/cure53/DOMPurify), a DOM-only library that requires [JSDOM](https://github.com/jsdom/jsdom) on Node.js
- [punkave/sanitize-html](https://github.com/punkave/sanitize-html), a Node.js-only library that depends on [htmlparser2](https://github.com/fb55/htmlparser2)

...as:
- [JavaScript (DOM-only, requires JSDOM for Node.js)](https://github.com/cure53/DOMPurify)
- [Node.js (depends on htmlparser2)](https://github.com/punkave/sanitize-html)

### CODE REVIEW

**Comment by rdela** [comment]
First off, I completely defer to your decisions about what goes in. I wrote in #101: 

> My cursory research into currently maintained libraries yielded two options [...] If OWASP contributors find both libraries adequate and satisfactory [...]

If the security posture of [punkave/sanitize-html](https://github.com/punkave/sanitize-html) is not sufficiently intolerant *and* obvious enough to warrant inclusion, then I think we should leave sanitize-html out and encourage Node.js devs to use DOMPurify with JSDOM. The fact that you have heard of DOMPurify and were surprised it was not there speaks volumes.

That said, sanitize-html does remove JS. From the README [opening section](https://github.com/punkave/sanitize-html/blob/master/README.md#sanitize-html):

> If a tag is not permitted, the contents of the tag are still kept, except for `script`, `style` and `textarea` tags.

Further down in ["What are the default options?"](https://github.com/punkave/sanitize-html/blob/master/README.md#what-are-the-default-options):

> ```js
> allowedTags: [ 'h3', 'h4', 'h5', 'h6', 'blockquote', 'p', 'a', 'ul', 'ol',
>   'nl', 'li', 'b', 'i', 'strong', 'em', 'strike', 'code', 'hr', 'br', 'div',
>   'table', 'thead', 'caption', 'tbody', 'tr', 'th', 'td', 'pre', 'iframe' ],
> allowedAttributes: {
>   a: [ 'href', 'name', 'target' ],
>   // We don't currently allow img itself by default, but this
>   // would make sense if we did. You could add srcset here,
>   // and if you do the URL is checked for safety
>   img: [ 'src' ]
> },
> // Lots of these won't come up by default because we don't allow them
> selfClosing: [ 'img', 'br', 'hr', 'area', 'base', 'basefont', 'input', 'link', 'meta' ],
> // URL schemes we permit
> allowedSchemes: [ 'http', 'https', 'ftp', 'mailto' ],
> allowedSchemesByTag: {},
> allowedSchemesAppliedToAttributes: [ 'href', 'src', 'cite' ],
> allowProtocolRelative: true
> ```

Later on:

> ### [Allowed URL schemes](https://github.com/punkave/sanitize-html/blob/master/README.md#allowed-url-schemes)
> 
> By default we allow the following URL schemes in cases where `href`, `src`, etc. are allowed:
> 
> ```js
> [ 'http', 'https', 'ftp', 'mailto' ]
> ```
> 
> You can override this if you want to:
> 
> ```javascript
> sanitizeHtml(
>   // teeny-tiny valid transparent GIF in a data URL
>   '',
>   {
>     allowedTags: [ 'img', 'p' ],
>     allowedSchemes: [ 'data', 'http' ]
>   }
> );
> ```
> 
> You can also allow a scheme for a particular tag only:
> 
> ```javascript
> allowedSchemes: [ 'http', 'https' ],
> allowedSchemesByTag: {
>   img: [ 'data' ]
> }
> ```
> 
> And you can forbid the use of protocol-relative URLs (starting with `//`) to access another site using the current protocol, which is allowed by default:
> 
> ```javascript
> allowProtocolRelative: false
> ```
> 
> ### [Discarding the entire contents of a disallowed tag](https://github.com/punkave/sanitize-html/blob/master/README.md#discarding-the-entire-contents-of-a-disallowed-tag)
> 
> Normally, with a few exceptions, if a tag is not allowed, all of the text within it is preserved, and so are any allowed tags within it.
> 
> The exceptions are:
> 
> `style`, `script`, `textarea`
> 
> If you wish to expand this list, for instance to discard whatever is found inside a `noscript` tag, use the `nonTextTags` option:
> 
> ```javascript
> nonTextTags: [ 'style', 'script', 'textarea', 'noscript' ]
> ```
> 
> Note that if you use this option you are responsible for stating the entire list. This gives you the power to retain the content of `textarea`, if you want to.
> 
> The content still gets escaped properly, with the exception of the `script` and `style` tags. *Allowing either `script` or `style` leaves you open to XSS attacks. Don't do that* unless you have good reason to trust their origin.


So by default...

- `script`, `style`, and `textarea` tags are removed and the entire contents are discarded.
- All attributes are removed from all tags except `href`, `name`, and `target` on `a` tags. On `href` only `http`, `https`, `ftp`, and `mailto` protocols are allowed.
- `iframe` tags are allowed by default but the `src` attribute is not. There is an [open issue about this](https://github.com/punkave/sanitize-html/issues/285) from 10 April where contributor Tom Boutell suggests `iframe` will be removed in the 2.x release since it is a breaking change and says:
  > as it currently stands the configuration does not make much sense because iframe is allowed, but src is not allowed for iframe.

Thought I would clarify all that to clear up any misunderstanding, but I will add a commit that removes `sanitize-html` on Monday unless I hear differently from @mackowski before then.

**Comment by mackowski** [comment]
Thank you for detailed answer!
I was obviously wrong and this library does sanitize javascript/xss payloads.
Many thanks for clarification. 
DOMPurify and Google Closure are well know and de facto standard javascript libs for this job. 
But the fact that I didn't know about sanitize-html does not mean that this is a wrong library!
On one side I am not sure if we have to have 3 js libs but on the other hand why not :)

@ThunderSon what do you think?

**Comment by rdela** [comment]
I am all for sticking to the de facto standard libs already familiar to OWASP contributors. While we are on the subject, should we rearrange the order to keep languages together and possibly add (JavaScript/Node.js) to the end of the Closure listing to be super explicit?

Like so:

**Other libraries that provide HTML Sanitization include:**
- [HTML sanitizer](https://github.com/google/closure-library/tree/master/closure/goog/html/sanitizer) from [Google Closure Library](https://developers.google.com/closure/library/) (JavaScript/Node.js)
- [DOMPurify](https://github.com/cure53/DOMPurify) (JavaScript, DOM-only, requires JSDOM for Node.js)
- [PHP HTML Purifier](http://htmlpurifier.org/)
- [Python Bleach](https://pypi.python.org/pypi/bleach)

**Comment by rdela** [comment]
Looks like maybe we should not capitalize [jsdom](https://github.com/jsdom/jsdom) either, and maybe we should lose "DOM-only" link that too?

So:

**Other libraries that provide HTML Sanitization include:**
- [HTML sanitizer](https://github.com/google/closure-library/tree/master/closure/goog/html/sanitizer) from [Google Closure Library](https://developers.google.com/closure/library/) (JavaScript/Node.js)
- [DOMPurify](https://github.com/cure53/DOMPurify) (JavaScript, requires [jsdom](https://github.com/jsdom/jsdom) for Node.js)
- [PHP HTML Purifier](http://htmlpurifier.org/)
- [Python Bleach](https://pypi.python.org/pypi/bleach)

**Comment by rdela** [comment]
We could also probably save lazy devs tons of time by linking to the [HTML sanitizer docs](https://google.github.io/closure-library/api/goog.html.sanitizer.HtmlSanitizer.html), not easy to find from the main [Closure link](https://developers.google.com/closure/library/). Although https://github.com/google/closure-library/blob/master/closure/goog/html/sanitizer/htmlsanitizer.js has a simple usage example currently on [Line 23](https://github.com/google/closure-library/blob/master/closure/goog/html/sanitizer/htmlsanitizer.js#L23).

So maybe adjust HTML sanitizer link to htmlsanitizer.js and add docs link at end?

**Other libraries that provide HTML Sanitization include:**
- [HTML sanitizer](https://github.com/google/closure-library/blob/master/closure/goog/html/sanitizer/htmlsanitizer.js) from [Google Closure Library](https://developers.google.com/closure/library/) (JavaScript/Node.js, [docs](https://google.github.io/closure-library/api/goog.html.sanitizer.HtmlSanitizer.html))
- [DOMPurify](https://github.com/cure53/DOMPurify) (JavaScript, requires [jsdom](https://github.com/jsdom/jsdom) for Node.js)
- [PHP HTML Purifier](http://htmlpurifier.org/)
- [Python Bleach](https://pypi.python.org/pypi/bleach)

**Comment by jmanico** [comment]
Please put https://www.owasp.org/index.php/OWASP_Java_HTML_Sanitizer_Project back it. It’s actively maintained by Mike Samuel via Google.

Aloha,
--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by jmanico** [comment]
Remember these are cheats. Please err on the side of brevity. Make sure to link vs include extra content.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by mackowski** [comment]
No worries Jim we did not deleted https://www.owasp.org/index.php/OWASP_Java_HTML_Sanitizer_Project it is recommended for Java :)

**Comment by mackowski** [comment]
@rdela I like your ideas about rearrange the order and improve linking to the closure docs and example.

**Comment by jmanico** [comment]
Woot!!!!

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by rdela** [comment]
@mackowski Updated with suggested changes from my last comment https://github.com/OWASP/CheatSheetSeries/pull/103#issuecomment-491411440

Travis build is failing but looks like that is only missing newlines in other cheatsheets?
https://travis-ci.com/OWASP/CheatSheetSeries/builds/111902594#L510

Want me to add them?

**Comment by righettod** [comment]
Give some time, i will fix it.
Ticket #105 assigned to me

**Comment by righettod** [comment]
I have added [info](https://github.com/OWASP/CheatSheetSeries/issues/105#issuecomment-492650331) about the TravisCI job issue to fix it in existing PR.

**Comment by rdela** [comment]
Thanks @righettod! PR updated and Travis is passing now ✅

**Comment by jmanico** [comment]
Train your Developers on Secure Coding

View this email in your browser (https://mailchi.mp/875ff264e773/manicode-security-june-2019?e=9676088248)


** Manicode Security
------------------------------------------------------------


** Secure Coding Education
June 2019 Update
------------------------------------------------------------
Secure Coding Classes
Thank you for being a customer, partner or associate of Manicode Security.

Manicode Security is now offering over a dozen different application security classes delivered by four different instructors.
* Ron Perris is now teaching classes in React, Node.js, Express and JavaScript secure coding.
* Jimmy Mesta is teaching classes in Kubernetes, AWS, GPC, Cloud Security and DevOps security.
* Dr. Philppe De Ryck is teaching classes in Advanced Web Security.
* And Jim Manico is teaching classes in a wide variety of Web and API Security topics.
* Classes are also available in Mobile Secure Coding and Penetration Testing.

You can download our full catalog here https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=f5e5c7f0ff&e=9676088248

Please drop us a line at info@manicode.com (mailto:info@manicode.com?subject=Info-June-2019) if you have any questions about our application security classes!
Manicode Security is Partnered with Bit Discovery

The one singular thing literally every information security professional agrees upon is that all organizations must have an inventory of all their internet-connected assets. This includes all websites, name servers, mail servers, IoT devices, blogs, and so on. Of course, an inventory is also required by most every information security standard. And the reason is simple, you cannot secure what you don’t know that you own. Period. Creating a complete asset inventory has proven exceptionally technically challenging, time-consuming, and labor intensive. This has to change. Bit Discovery’s mission, having invested the last several years creating a fantastic product, is making sure every organization has a complete asset inventory. Instantly created. Automatically updated.

Please visit https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=a6b3d01345&e=9676088248 for more information or email contact@bitdiscovery.com (mailto:contact@bitdiscovery.com)  to schedule a live demo to create an asset inventory for your organization and receive a free trial account.

============================================================

This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
why did I get this? (https://manicode.us19.list-manage.com/about?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=9676088248&c=b62483214f)     unsubscribe from this list (https://manicode.us19.list-manage.com/unsubscribe?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=9676088248&c=b62483214f)     update subscription preferences (https://manicode.us19.list-manage.com/profile?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=9676088248)
Manicode Security . PO Box 676 . Anahola, HI 96703-0676 . USA

Email Marketing Powered by Mailchimp
http://www.mailchimp.com/monkey-rewards/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=monkey_rewards&aid=3b283d304057d06aaba6dc8fb&afl=1

**Comment by jmanico** [comment]
Train your Developers on Secure Coding

View this email in your browser (https://mailchi.mp/875ff264e773/manicode-security-june-2019?e=c1b1864aeb)


** Manicode Security
------------------------------------------------------------


** Secure Coding Education
June 2019 Update
------------------------------------------------------------
Secure Coding Classes
Thank you for being a customer, partner or associate of Manicode Security.

Manicode Security is now offering over a dozen different application security classes delivered by four different instructors.
* Ron Perris is now teaching classes in React, Node.js, Express and JavaScript secure coding.
* Jimmy Mesta is teaching classes in Kubernetes, AWS, GPC, Cloud Security and DevOps security.
* Dr. Philppe De Ryck is teaching classes in Advanced Web Security.
* And Jim Manico is teaching classes in a wide variety of Web and API Security topics.
* Classes are also available in Mobile Secure Coding and Penetration Testing.

You can download our full catalog here https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=f5e5c7f0ff&e=c1b1864aeb

Please drop us a line at info@manicode.com (mailto:info@manicode.com?subject=Info-June-2019) if you have any questions about our application security classes!
Manicode Security is Partnered with Bit Discovery

The one singular thing literally every information security professional agrees upon is that all organizations must have an inventory of all their internet-connected assets. This includes all websites, name servers, mail servers, IoT devices, blogs, and so on. Of course, an inventory is also required by most every information security standard. And the reason is simple, you cannot secure what you don’t know that you own. Period. Creating a complete asset inventory has proven exceptionally technically challenging, time-consuming, and labor intensive. This has to change. Bit Discovery’s mission, having invested the last several years creating a fantastic product, is making sure every organization has a complete asset inventory. Instantly created. Automatically updated.

Please visit https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=a6b3d01345&e=c1b1864aeb for more information or email contact@bitdiscovery.com (mailto:contact@bitdiscovery.com)  to schedule a live demo to create an asset inventory for your organization and receive a free trial account.

============================================================

This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
why did I get this? (https://manicode.us19.list-manage.com/about?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=c1b1864aeb&c=b62483214f)     unsubscribe from this list (https://manicode.us19.list-manage.com/unsubscribe?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=c1b1864aeb&c=b62483214f)     update subscription preferences (https://manicode.us19.list-manage.com/profile?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=c1b1864aeb)
Manicode Security . PO Box 676 . Anahola, HI 96703-0676 . USA

Email Marketing Powered by Mailchimp
http://www.mailchimp.com/monkey-rewards/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=monkey_rewards&aid=3b283d304057d06aaba6dc8fb&afl=1

**Comment by jmanico** [comment]
Train your Developers on Secure Coding

View this email in your browser (https://mailchi.mp/875ff264e773/manicode-security-june-2019?e=c51115e424)


** Manicode Security
------------------------------------------------------------


** Secure Coding Education
June 2019 Update
------------------------------------------------------------
Secure Coding Classes
Thank you for being a customer, partner or associate of Manicode Security.

Manicode Security is now offering over a dozen different application security classes delivered by four different instructors.
* Ron Perris is now teaching classes in React, Node.js, Express and JavaScript secure coding.
* Jimmy Mesta is teaching classes in Kubernetes, AWS, GPC, Cloud Security and DevOps security.
* Dr. Philppe De Ryck is teaching classes in Advanced Web Security.
* And Jim Manico is teaching classes in a wide variety of Web and API Security topics.
* Classes are also available in Mobile Secure Coding and Penetration Testing.

You can download our full catalog here https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=f5e5c7f0ff&e=c51115e424

Please drop us a line at info@manicode.com (mailto:info@manicode.com?subject=Info-June-2019) if you have any questions about our application security classes!
Manicode Security is Partnered with Bit Discovery

The one singular thing literally every information security professional agrees upon is that all organizations must have an inventory of all their internet-connected assets. This includes all websites, name servers, mail servers, IoT devices, blogs, and so on. Of course, an inventory is also required by most every information security standard. And the reason is simple, you cannot secure what you don’t know that you own. Period. Creating a complete asset inventory has proven exceptionally technically challenging, time-consuming, and labor intensive. This has to change. Bit Discovery’s mission, having invested the last several years creating a fantastic product, is making sure every organization has a complete asset inventory. Instantly created. Automatically updated.

Please visit https://manicode.us19.list-manage.com/track/click?u=3b283d304057d06aaba6dc8fb&id=a6b3d01345&e=c51115e424 for more information or email contact@bitdiscovery.com (mailto:contact@bitdiscovery.com)  to schedule a live demo to create an asset inventory for your organization and receive a free trial account.

============================================================

This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
why did I get this? (https://manicode.us19.list-manage.com/about?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=c51115e424&c=b62483214f)     unsubscribe from this list (https://manicode.us19.list-manage.com/unsubscribe?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=c51115e424&c=b62483214f)     update subscription preferences (https://manicode.us19.list-manage.com/profile?u=3b283d304057d06aaba6dc8fb&id=94b725b0f5&e=c51115e424)
Manicode Security . PO Box 676 . Anahola, HI 96703-0676 . USA

Email Marketing Powered by Mailchimp
http://www.mailchimp.com/monkey-rewards/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=monkey_rewards&aid=3b283d304057d06aaba6dc8fb&afl=1

**Pull request merged**
