### PR TITLE
Fix typo "punditto"

### PR DESCRIPTION
**Pull request by Archieru**
Just a small typo 
"or punditto do this" => "or pundit to do this" 
:smiley:

### CODE REVIEW

**Comment by mackowski** [comment]
@Archieru thanks for this PR, we will merge it after we fix #105

**Comment by righettod** [comment]
I will fix the issue on the CI job ASAP.
The issue #105 has been created to track that point.

**Comment by righettod** [comment]
I have added [info](https://github.com/OWASP/CheatSheetSeries/issues/105#issuecomment-492650331) about the TravisCI job issue to fix it in existing PR.

**Comment by mackowski** [comment]
@Archieru can you fix the build? The info how to do this is in #105

**Comment by mackowski** [comment]
Thank you!

**Pull request merged**
