### PR TITLE
New Addition: Infrastructure as Code Security CheatSheet

### PR DESCRIPTION
**Pull request by ragashreeshekar**
Infrastructure as code (IaC) also known as software-defined infrastructure, allows the configuration and deployment of infrastructure components faster with consistency by allowing them to be defined as a code and also enables repeatable deployments across environments.

Here are some of the security best practices for IaC that can be easily integrated to the Software Development Lifecycle.

### CODE REVIEW

**Comment by jmanico** [comment]
There are large number of markdown errors, can you fix this before we push this PR? If you need help I can take care of it later...

**Comment by ragashreeshekar** [comment]
Thanks @jmanico, the link errors have been addresses. Request you to review and merge the same

**Review by mackowski — APPROVED** [review]
LGTM!

**Comment by mackowski** [comment]
Thanks again @ragashreeshekar

**Pull request merged**
