### PR TITLE
secrets management: update lifetime section

### PR DESCRIPTION
**Pull request by vixentael**
As someone who works in cryptography and builds complicated key management protocols, I can't stay away of this party 🥳 

This PR just adds small changes and clarifications, as part of #124.

Things done:
- added details to lifecycle of the keys.
- changed all "SSL" references to "TLS".
- added NIST guideline that is ALL about key management.

After merging #829 and #830 we should merge master here to avoid conflicts.

@commjoen @jmanico @zbraiterman take a look!

### CODE REVIEW

**Comment by vixentael** [comment]
Changed base branch to `cheatsheets-4`. 

I still have a feeling that after merging #829 and #830, I'll need to come back here and fix conflicts. Well, let's move gradually.

**Comment by vixentael** [comment]
@commjoen ok, the changes are in `cheatsheets-4`. What's the plan now? Should I make new PR `cheatsheets-4` to `master`, or you'll handle it?

**Comment by commjoen** [comment]
@vixentael , it just got merged so we can extend on it. Thank you so much for your help!

**Comment by commjoen** [comment]
Ah it got merged after the PR of cheatsheets-4 got merged...  I have created a new PR https://github.com/OWASP/CheatSheetSeries/pull/832 and asked @jmanico to merge it :).

**Pull request merged**
