### PR TITLE
Adding some sample encryption code to the DotNet cheatsheet

### PR DESCRIPTION
**Pull request by tghosth**
Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- ~~In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).~~
- [x] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [x] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- ~~All your assets are stored in the **assets** folder.~~
- ~~All the images used are in the **PNG** format.~~
- [x] Any references to websites have been formatted as [TEXT](URL)
- [x] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [x] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

Thank you again for your contribution :smiley:

### CODE REVIEW

**Comment by tghosth** [comment]
Hi @scottbrady91 I would appreciate your thoughts on this example code :) I got some of it from your blog and the rest I'd appreciate another pair of eyes anyway :)

**Comment by tghosth** [comment]
I'm always a little nervous with crypto code and this is particularly complicated. If you are confident with it then you can merge it. If you would rather wait to see if any other .net experts pitch in, that is also fine.

**Review by mackowski — APPROVED** [review]
Looks good

**Comment by tghosth** [comment]
Note that I might subsequently make changes based on some similar Java code in #1146

**Pull request merged**
