### PR TITLE
.NET Cheat Sheet spruce up

### PR DESCRIPTION
**Pull request by szh**
I've recently been doing some work in .NET after a long break, and I decided it would be a good time to review the .NET Security Cheat Sheet and clean it up a bit. I've identified several things that can be improved and will get to them as I can. I'll mark this PR as ready to review once I have it in a good spot, but feel free to add comments even before then.

### CODE REVIEW

**Review by jmanico — DISMISSED** [review]

**Review by jmanico — DISMISSED** [review]

**Comment by jmanico** [comment]
What a great update. Can you check out the lint errors before I commit?

cheatsheets/DotNet_Security_Cheat_Sheet.md:1142 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cheatsheetseries@1.0.1 lint-markdown: `markdownlint ./cheatsheets/ --ignore node_modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cheatsheetseries@1.0.1 lint-markdown script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by szh** [comment]
It's still a draft, please don't merge yet!

**Comment by kwwall** [comment]
Hey @jmanico and @mackowski -- I'm going to suggest that we ask @sempf to review this as well.  Bill participated (and I think, at one point _led_) the OWASP .NET Project and he's write several .NET related books, the latest being on C# 7.0. (See https://www.amazon.com/stores/Bill-Sempf/author/B001IOBM1S for a list.)

**Comment by sempf** [comment]
All in all I like the reorganization a lot.  I need to go through it and make sure there are no technical errors (just on general principle) and I'll try and have that done before you finish your edits, @zsh.  And thanks for doing this!

**Comment by kwwall** [comment]
Bill, thanks for looking.

**Comment by jmanico** [comment]
Would you all  like me to clean up the link errors and then merge it, or is this still a work in progress?

**Comment by szh** [comment]
@jmanico still a WIP. I've been super busy but hope to finish this up sometime this month. In particular I want to update to referencing the latest Top 10 list instead of the old version.

**Comment by Jure-BB** [comment]
> Not sure how I would recommend integrating these differences into the Cheat Sheet though. I don't think it requires a separate sheet, but I am up for debate on that. Maybe find the diffs, and just make subheadings?

The .NET Framework is no longer going to receive any feature updates, so a Cheat Sheet targeting the .NET Framework should remain fairly static. It's probably going to be easier to maintain separate Cheat Sheets, as only the Cheat Sheet targeting .NET 6+ will need to be updated most of the time.

**Comment by sempf** [comment]
> The .NET Framework is no longer going to receive any feature updates, so a Cheat Sheet targeting the .NET Framework should remain fairly static.

That's a pretty dang good point. I'll leave how best to implement that to the cheat sheet gurus.

**Comment by mackowski** [comment]
IMO it will be more useful if we target .NET 6+. 
We can create some small static .NET Framework cheatsheet if we will find that we have some good recommendations for it but the future is .NET 6+

**Comment by szh** [comment]
Any ideas what I should add for A08 Software and Data Integrity Failures, which is new to the 2021 Top 10 list? Is there anything .NET specific for this topic?

**Comment by jmanico** [comment]
Would you like me to commit the work so far?

**Comment by szh** [comment]
@jmanico No thanks, still a draft in progress

**Comment by jmanico** [comment]
May I suggest several small PR's vs one big one? :)

**Comment by szh** [comment]
@jmanico yeah it probably would've been smart to start it out that way but now that it's gotten so big and it's 80% done I don't want to spend the time to split it up

**Comment by jmanico** [comment]
All good, we appreciate your efforts!

**Comment by szh** [comment]
OK so I'm just about ready to mark this as ready for review. I didn't go into handling .NET Framework vs Core at this point - that should be a separate effort. As of now I left it in the current state where it sort of addresses both.

The main changes I did were reorganizing the sections, and updating it to base itself on the OWASP Top 10 2021 list instead of the 2017 one.

**Comment by jmanico** [comment]
Merged. :) Can you please do small commits from this point on and I'll be responsive? This is massively excellent work.

**Comment by szh** [comment]
@jmanico Yes absolutely. Thanks so much!

**Pull request merged**
