### PR TITLE
Update Securing_Cascading_Style_Sheets_Cheat_Sheet.md

### PR DESCRIPTION
**Pull request by GeoMarkou**
* Improve the advice of Defense Mechanism 2
* Fix dead link in Defense Mechanism 3 (noticed while fixing above, might as well while I'm here)
* Add some clarification to Defense Mechanism 3

This PR covers issue #1027.

### CODE REVIEW

**Review by jmanico — DISMISSED** [review]

**Comment by jmanico** [comment]
This is a great edit to this cheatsheet, but can you kindly clean up some of the lint errors?

cheatsheets/Securing_Cascading_Style_Sheets_Cheat_Sheet.md:56:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/Securing_Cascading_Style_Sheets_Cheat_Sheet.md:57:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/Securing_Cascading_Style_Sheets_Cheat_Sheet.md:58:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/Securing_Cascading_Style_Sheets_Cheat_Sheet.md:59:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]

**Review by jmanico — APPROVED** [review]

**Comment by mackowski** [comment]
@jmanico you must revert these changes - this PR had a lint errors and now the side will not build, and all new PR will be failing.

**Comment by GeoMarkou** [comment]
It's complaining about line `57:166`
> .css file

Aren't file extensions usually lowercase?

**Comment by jmanico** [comment]
Its fixed and merged

**Comment by jmanico** [comment]
> @jmanico you must revert these changes - this PR had a lint errors and now the side will not build, and all new PR will be failing.

I fixed them Kuba, all set?

**Pull request merged**
