### PR TITLE
TLS_Cipher_String_Cheat_Sheet: added markdown tables

### PR DESCRIPTION
**Pull request by valentinxxx**

### CODE REVIEW

**Comment by valentinxxx** [comment]
Do you think is it possible to add `<br>` as an `allowed_elements` to markdownlint rule `MD033 - Inline HTML`?

**Comment by righettod** [comment]
The need for usage of `<br>` in your context is legit so you can use this syntax to add `<br>` in your MD table:

```html
<!-- markdownlint-disable MD033 -->
Your MD table here
<!-- markdownlint-enable MD033 -->
```
It allow you to use HTML tags in your MD table, but please limit usage to `<br>` tag.

**Comment by righettod** [comment]
You can also remove link to the image versions of the both tables if your contribution replace them.

**Comment by valentinxxx** [comment]
I've commited the `markdownlint-disable` comments.
There is background colorization in the image versions, which we cannot reproduce in markdown.
Do you think is it OK to replace them?

**Comment by righettod** [comment]
We can go in this way, for me it is not an issue to have the both tables
without the colorization. If needed, we will add legend indicators later.
I will merge the PR soon.
Thank you very much for your contribution.

**Pull request merged**
