### PR TITLE
Add "Logging" subsection to the microservice security cheat sheet

### PR DESCRIPTION
**Pull request by AlexB1986**
Hi Team!
A would like to add "Logging" subsection to microservice security cheat sheet with design recommendation on how to implement logging subsystem in microservice-based systems.

--
Alexander Barabanov
Advanced Software Technology Lab
Huawei

### CODE REVIEW

**Comment by jmanico** [comment]
There are some grammatical errors - but this otherwise looks good, when I have time I'll commit and fix some of the language issues and get this live.

Thank you!

**Comment by mackowski** [comment]
Hey @jmanico when you will have time for this? Or can you just add comments here to the lines with advice what needs to be changed?

**Comment by jmanico** [comment]
I’ll take this on tonight! :)

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by jmanico** [comment]
all done, I also committed a grammar fix

**Pull request merged**
