### PR TITLE
Create OAuth2_Cheat_Sheet

### PR DESCRIPTION
**Pull request by csfreak92**
Draft OAuth 2.0 cheat sheet.

Thank you for submitting a Pull Request (PR) to the Cheat Sheet Series. 

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [ ] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [ ] All your assets are stored in the **assets** folder.
- [ ] All the images used are in the **PNG** format.
- [ ] Any references to websites have been formatted as [TEXT](URL)
- [ ] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #1168.

Thank you again for your contribution :smiley:

### CODE REVIEW

**Comment by szh** [comment]
I didn't get a chance to review the content yet, but please rename the file to end in `.md`.

**Review by jmanico — APPROVED** [review]
happy to push this live and continue to work on it

**Review by jmanico — CHANGES_REQUESTED** [review]
And yes we need the filename changed :)

**Comment by csfreak92** [comment]
> happy to push this live and continue to work on it

@jmanico, I will keep updating and work on it to be at par with the OAuth 2.0 requirements I have for ASVS. I can spot a few things that Josh has made me clarify in the ASVS side of things. I will do the same for this one. Please bear with me as there are two documents + a few dozen more that I am looking at to make it look parallel at least. :)

**Review by jmanico — CHANGES_REQUESTED** [review]
There are quite a few lint errors

cheatsheets/OAuth2_Cheat_Sheet.md:1 MD041/first-line-heading/first-line-h1 First line in file should be a top level heading [Context: "## OAuth 2.0 Protocol Cheatshe..."]
cheatsheets/OAuth2_Cheat_Sheet.md:3:525 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:5:16 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:5:[15](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:16) MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
cheatsheets/OAuth2_Cheat_Sheet.md:7:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:7:362 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:8:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:8:400 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:9:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:9:303 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:10:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:11:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:11:[16](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:17)7 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:12:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:12:167 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:14 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
cheatsheets/OAuth2_Cheat_Sheet.md:[17](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:18):1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:[18](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:19):1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:[19](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:20):1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:19:267 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:[20](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:21):1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:[21](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:22):1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:21:123 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:23 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
cheatsheets/OAuth2_Cheat_Sheet.md:26:277 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:28:427 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:30:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:31:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:31:280 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:32:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:32:184 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:33:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:33:[22](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:23)0 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:35 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
cheatsheets/OAuth2_Cheat_Sheet.md:38:470 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:40:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:40:478 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:42 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
cheatsheets/OAuth2_Cheat_Sheet.md:43:[27](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:28) MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:45:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:45:212 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:46:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:48 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
cheatsheets/OAuth2_Cheat_Sheet.md:51:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:52:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:52:610 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:53:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:53:605 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:55 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
cheatsheets/OAuth2_Cheat_Sheet.md:58:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:58:199 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:60 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
cheatsheets/OAuth2_Cheat_Sheet.md:63:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:63:401 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:65 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
cheatsheets/OAuth2_Cheat_Sheet.md:68:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:68:207 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:69:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
cheatsheets/OAuth2_Cheat_Sheet.md:69:2[29](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:30) MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:[71](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:72) MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
cheatsheets/OAuth2_Cheat_Sheet.md:[72](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:73) MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 3]
cheatsheets/OAuth2_Cheat_Sheet.md:[73](https://github.com/OWASP/CheatSheetSeries/actions/runs/7014629171/job/19099187612?pr=1237#step:5:74):12 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]

**Comment by jmanico** [comment]
> > happy to push this live and continue to work on it
> 
> @jmanico, I will keep updating and work on it to be at par with the OAuth 2.0 requirements I have for ASVS. I can spot a few things that Josh has made me clarify in the ASVS side of things. I will do the same for this one. Please bear with me as there are two documents + a few dozen more that I am looking at to make it look parallel at least. :)

Oh I know how rough this part of ASVS is, I promise to help once the first version is live!

**Review by jmanico — APPROVED** [review]
Lets get this beauty live

**Comment by szh** [comment]
Hey @csfreak92, there are still three lint errors:

cheatsheets/OAuth2_Cheat_Sheet.md:5:15 MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: ':']
cheatsheets/OAuth2_Cheat_Sheet.md:39:27 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
cheatsheets/OAuth2_Cheat_Sheet.md:63:12 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]

**Comment by jmanico** [comment]
I'll fix these lint errors soon.

**Pull request merged**
