### PR TITLE
New Addition: an npm security cheatsheet 

### PR DESCRIPTION
**Pull request by lirantal**
**New Addition: an npm security cheatsheet for JavaScript and Node.js developers.**

I don't have experience with other package managers, but I think it'll set a great start to begin setting those best practices on how to securely consume open source libraries in a way that won't be subjecting you to supply chain attacks, as well as providing tips for maintainers to level up their security game.

---

> :triangular_flag_on_post: If your PR is related to grammar/typo mistakes, please double-check the file for other mistakes in order to fix all the issues in the current cheat sheet.

Please make sure that for your contribution:

- [ ] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [ ] All the markdown files do not raise any validation policy violation, see the [policy](https://github.com/OWASP/CheatSheetSeries/actions?query=workflow%3A%22Markdown+Link+Check%22).
- [ ] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md#markdown).
- [ ] All your assets are stored in the **assets** folder.
- [ ] All the images used are in the **PNG** format.
- [ ] Any references to websites have been formatted as [TEXT](URL)
- [ ] You verified/tested the effectiveness of your contribution (e.g., the defensive code proposed is really an effective remediation? Please verify it works!).
- [ ] The CI build of your PR pass, see the build status [here](https://github.com/OWASP/CheatSheetSeries/actions).

If your PR is related to an issue, please finish your PR text with the following line:

This PR covers issue #<insert number here>.

Thank you again for your contribution :smiley:

### CODE REVIEW

**Comment by mackowski** [comment]
Thanks @lirantal I will review this later this week :)

**Comment by lirantal** [comment]
Sounds good!

**Comment by jmanico** [comment]
I did a quick review and really like this. This is a good way we can reference Snyk since its just Synk research not a Synk product per say

**Review by mackowski — DISMISSED** [review]

**Comment by mackowski** [comment]
Looks good from my side but:
 - @lirantal this PR is currently adding file to the cheatsheets_draft - to make it live we need to change directory to  'cheatsheets'
 - @jmanico I do not know if you noticed that, but this CS is almost a copy of the blogpost from Snyk blog. Last time we did much more editing. Personally, I think that this is fine, for this article, but I just want to highlight it for you :)

**Comment by jmanico** [comment]
The blog post copy is fine. As long as we are *not* directly endorsing a 
company or discussing the merits of any commercial products, the rest of 
the copy of fine. I think these are good donations to the foundation! :)

- Jim

**Comment by lirantal** [comment]
I've actually edited out all the "getting started with Snyk" parts of the scanning vulns for example and some other parts. I did leave the relevant information to vulnerabilities on the Snyk database, or the deep research around them, as that relates to the technical topic. 

I'm ok with this on my end as well but @mackowski if you feel you need to make any more edits, you're more than welcome to :-)

Would you like me to update the PR to move the file from current folder to the finished cheatsheets ones?

**Comment by mackowski** [comment]
@lirantal yes please update the PR to move the file from current folder to the main cheatsheets folder and we will merge it :)

**Comment by lirantal** [comment]
@mackowski I fixed all the linting issues across markdown and terminology. Ready on my end :-)

**Review by mackowski — APPROVED** [review]

**Comment by mackowski** [comment]
Ok, lets release it ;) Thanks @lirantal for another awesome cheatsheet :)

**Comment by lirantal** [comment]
Yay! Super excited for it :-)

**Comment by mackowski** [comment]
Here it is: https://cheatsheetseries.owasp.org/cheatsheets/npm_Security_CheatSheet.html 🥇

**Pull request merged**
