### PR TITLE
initial update of PHP config sheet 

### PR DESCRIPTION
**Pull request by danehrlich1**
Thank you for submitting a Pull Request to the Cheat Sheet Series. 

Please make sure that for your contribution:

- [x] In case of a new Cheat Sheet, you have used the [Cheat Sheet template](https://github.com/OWASP/CheatSheetSeries/blob/master/templates/New_CheatSheet.md).
- [x] All the markdown files do not raise any validation policy violation, see policy [here](https://github.com/OWASP/CheatSheetSeries#editor--validation-policy).
- [x] All the markdown files follow these [format rules](https://github.com/OWASP/CheatSheetSeries#conversion-rules).
- [x] All your assets are stored in the **assets** folder.
- [x] All the images used are in the **PNG** format.
- [x] Any references to website have been formatted as [TEXT](URL)
- [x] You verified/tested the effectiveness of your contribution (e.g.: defensive code proposed is really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR text with the following line:

```
This PR covers issue #3 .
```

Thanks you again for your contribution :smiley:

### CODE REVIEW

**Comment by danehrlich1** [comment]
NOTE: This pull request is NOT done, but wanted to get the ball rolling to make things exciting :)
Will throw in a couple commits in the next few days to finish this. This includes the Apache and hopefully Nginx sections.

**Comment by righettod** [comment]
Thanks for the info.
I will merge the PR when the CS will be ready for release.
Do not forget to complete the checklist of the PR initial message.
Thanks in advance.

**Comment by danehrlich1** [comment]
@righettod This cheatsheet in reference to #3 is ready to go. 

It looks like it matches all parts of the contributing checklist, please let  me know if any edits need to be made though and I will get on it.

I plan on updating this sheet in a couple of months with more detailed / concise information if that is okay.

**Comment by righettod** [comment]
Hi, can you move the file into the folder  **cheatsheets** in order to allow it to be audited by Travis ?

Thanks you in advance

**Comment by danehrlich1** [comment]
@righettod Moved to correct folder...waiting for Travis CI checks and then should be good to merge

**Comment by righettod** [comment]
@danehrlich1 I let you fix the build before to review the PR 😃

**Comment by righettod** [comment]
Hi, do you need some helps? all is ok?

**Comment by danehrlich1** [comment]
Can you take care of the linting thing so the tests will pass and we can merge this pull request? I can’t get VS Code working right.

**Comment by righettod** [comment]
What is the issue with VSCode ?
You do not need VSCode to fix the issue, you can fix them using your editor and let PR give you a feedback (PR build in less than 2 minutes and issues are mentioned in the console).
VSCode is only used to allow to work on CS like than developing in a IDE ans have a direct feedback...

**Comment by righettod** [comment]
Can I help you to setup the local linter and VSCode ?

**Comment by righettod** [comment]
I have handled the linter issues  and updated the content to take also content from the wiki.

**Pull request merged**
