### PR TITLE
README Rewrite

### PR DESCRIPTION
**Pull request by ThunderSon**
- Full README rewrite.
- Moved Conversion rules to contributing guide
- Basic update to the contributing guide

Another PR will be created to remove the preface (we don't need that) and update the showcased page on the website, as well as updating the contributing guide.

### CODE REVIEW

**Comment by mackowski** [comment]
I will not merge it for now to let @rbsec to review.

**Comment by rbsec** [comment]
@ThunderSon I made some changes to what you'd done - mostly minor wording and style ones.

The contribution guide changes got a bit bigger - we had two different sections about Markdown styling which I combined.

**Comment by ThunderSon** [comment]
A small touch on the contributing guide

**Comment by ThunderSon** [comment]
Should we handle the preface in here? I feel like removing that file and just replacing it with the README on the main website.

**Comment by jmanico** [comment]
+1 agree

--
Jim Manico
@Manicode

**Comment by ThunderSon** [comment]
After giving it a second thought, the preface needs to stay separate as the content that should be shown on the website needs to differ a bit from the README (which focuses more on GitHub). I'll give it another look later on.

**Pull request merged**
